### ISSUE TITLE
can't get token when working on iis

### ISSUE THREAD

**Issue by SaqoKH** [stepanbenes/api-for-nopcommerce#27]
hi, there's "Not Found" on ClientApp when trying to get token  on IIS.
it's working fine on localhost, iis express
can you help?

**Comment by stepanbenes** [comment]
Do you have correct URL including port number?

**Comment by SaqoKH** [comment]
issue has been fixed.
But now I have another one
I want to delete/change product's some properties (ProductDTO), I remove these properties but when run clientapp these properties appear again.
how can I modify/delete properties?

**Comment by stepanbenes** [comment]
Can you post the exact query, request body and error message that are you getting?

**Comment by SaqoKH** [comment]
I'm not getting error , I want to modify ProductDTO schema in swagger.json file, add some new fields for product.  there is a problem that I can't find swagger.json file in my project in order to modify it.

**Comment by stepanbenes** [comment]
What are you trying to achieve? swagger.json is just a description of an existing api, adding fields to it does not do anything.

(the file is generated at runtime and can be accessed at url: `/api/swagger/v1/swagger.json`)

And `ProductDTO` class is just a mapping to `Product` entity located in nopcommerce repository. You have to change the database schema in order to modify properties of a product.

**Comment by SaqoKH** [comment]
I figure out. Thx
